import gradio as gr

from generator import ask, format_response
from ingest import chunk_document, load_documents
from retriever import embed_and_store, get_collection


def run_ingestion():
    """
    Load documents, chunk them, and store in ChromaDB.

    If the vector store is already populated, ingestion is skipped.
    To re-ingest (e.g. after changing your chunking strategy), delete the
    ./chroma_db folder and restart the app.
    """
    collection = get_collection()

    if collection.count() > 0:
        print(f"Vector store already populated ({collection.count()} chunks). Skipping ingestion.")
        print("To re-ingest, delete the ./chroma_db folder and restart.")
        return

    print("Ingesting documents...")
    documents = load_documents()
    all_chunks = []

    for doc in documents:
        chunks = chunk_document(doc["text"], doc["source"])
        all_chunks.extend(chunks)

    if all_chunks:
        embed_and_store(all_chunks)
        print(f"Ingestion complete. {len(all_chunks)} chunks stored.")
    else:
        print(
            "\nNo chunks produced. Make sure chunk_document() is implemented in ingest.py\n"
            "and that you have .txt files in the documents/ folder.\n"
            "The app will start, but won't be able to answer questions yet.\n"
        )


def handle_query(question):
    """Run retrieval + generation; return answer and review citations separately."""
    if not question.strip():
        return "", ""
    result = ask(question)
    citations = "\n\n".join(result["citations"]) if result.get("citations") else ""
    return result["answer"], citations


def chat(message, history):
    """ChatInterface handler — answer with sources appended programmatically."""
    if not message.strip():
        return ""
    return format_response(ask(message))


with gr.Blocks(
    theme=gr.themes.Soft(primary_hue="blue"),
    title="The Unofficial Guide",
) as demo:

    gr.HTML("""
    <div style="text-align: center; padding: 1rem 0;">
        <h1 style="margin: 0;">The Unofficial Guide</h1>
        <p style="color: #666; margin-top: 0.5rem;">
            Ask about Stony Brook CS professors — answers grounded in Rate My Professors reviews.
        </p>
    </div>
    """)

    with gr.Row():
        with gr.Column(scale=3):
            question_box = gr.Textbox(
                label="Your question",
                placeholder='e.g. "Does Paul Fodor record his lectures for CSE 114?"',
                lines=2,
            )
            ask_btn = gr.Button("Ask", variant="primary")

            with gr.Row():
                answer_box = gr.Textbox(label="Answer", lines=10, interactive=False)
                sources_box = gr.Textbox(label="Retrieved from", lines=24, interactive=False)

            ask_btn.click(handle_query, inputs=question_box, outputs=[answer_box, sources_box])
            question_box.submit(handle_query, inputs=question_box, outputs=[answer_box, sources_box])

            gr.Examples(
                examples=[
                    "Does Paul Fodor record his lectures for CSE 114?",
                    "What Rate My Professor tags do students assign to Christopher Kane for CSE 307?",
                    "What do students say about I.V. Ramakrishnan's CSE 596 class?",
                    "What's the best dining hall at Stony Brook?",
                ],
                inputs=question_box,
            )

        with gr.Column(scale=1, min_width=180):
            gr.HTML("""
            <div style="padding: 1rem; background: #f8f9fa; border-radius: 8px;">
                <h3 style="margin-top: 0;">How it works</h3>
                <p style="font-size: 0.9rem; color: #555;">
                    Type a question and click <strong>Ask</strong>.
                    The system retrieves relevant student reviews, then generates
                    an answer using only those reviews.
                </p>
                <p style="font-size: 0.85rem; color: #777;">
                    Sources are listed separately on the right — not generated by the LLM.
                    If the info isn't in the loaded reviews, the guide will say so.
                </p>
            </div>
            """)

if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("  The Unofficial Guide — starting up")
    print("=" * 50 + "\n")
    run_ingestion()
    demo.launch()
